import type { Metadata } from "next";
import { Encode_Sans } from "next/font/google";
import "@fortawesome/fontawesome-free/css/all.css"
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import { Navbar } from "./_component/Navbar/Navbar";
import Footer from "./_component/Footer/Footer";
import UserProvider from "src/UserProvider";
import CountProvider from "src/CountProvider";

const Encode_SansFont = Encode_Sans({
  subsets: ['latin'],
  weight: ['100', '400', '800']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Encode_SansFont.className}`}
      >
        <UserProvider>
        <CountProvider>

          <Toaster />

          <Navbar />
          <main className="p-5">
            {children}
          </main>
          <Footer />

        </CountProvider>
          
        </UserProvider>
      </body>
    </html>
  );
}
